name: backend
description: An empty Aqueduct application.
version: 0.0.1
author: stable|kernel <jobs@stablekernel.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  aqueduct: ^4.0.0-b1
  analyzer: '>=0.39.4 <0.41.0'

dev_dependencies:
  test: ^1.0.0
  aqueduct_test: ^2.0.0-b1
dependency_overrides:
  aqueduct:
    path: /home/rr/Programs/aqueduct/aqueduct/
  aqueduct_test:
    path: /home/rr/Programs/aqueduct/aqueduct_test/
